version: '3.2'
services:
  demo-dev-cache-redis:
    image: redis:latest
    command: redis-server --port 6379 --requirepass p8WOmXgzZg  --appendonly yes
    ports:
      - 6379:6379
  demo-dev:
    build: .
    volumes:
      - ..:/home/developer/Demo
